[program:queue-worker]
process_name=%(program_name)s_%(process_num)02d
command=/var/www/html/services/docker/worker-entrypoint.sh queue php artisan queue:work --queue=sync,default --tries=5 --timeout=0
autostart=true
autorestart=true
numprocs=1
user=www-data
redirect_stderr=true
stdout_logfile=/var/www/html/storage/logs/queue.log
